// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type HealthPayload struct {
	CanReachGraphQLProxy bool `json:"canReachGraphQLProxy"`
	CanReachMicroservice bool `json:"canReachMicroservice"`
	AccessTokenIsValid   bool `json:"accessTokenIsValid"`
}
